name: Test
on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Data
        run: |
          python getData.py ${{ github.event.issue.body }}
        
